[project]
name = 'Hobby-Graveyard-Archaeological-Survey'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.enthusiasm-half-life-calculator]
path = 'contracts/enthusiasm-half-life-calculator.clar'
clarity_version = 3
epoch = '3.2'

[contracts.starter-kit-depreciation-tracker]
path = 'contracts/starter-kit-depreciation-tracker.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
